### ISSUE TITLE
Coller le footer en bas de la page

### ISSUE THREAD

**Issue by BrummbaerFr** [BrummbaerFr/hARDcipher#1]
Plusieurs recherches Google, mais j'arrive pas à coller ce `footer` en bas de la page.
Si vous pouvez aider ..
cf index.html et style.css

**Comment by snakypex** [comment]
Je suis au Resto je regarde en rentrant ;) Tu veux dire quoi en gros ? Que ce soit en bas de la page du navigateur et que au dessus ça reste vide ?

Envoyé de mon iPhone

**Comment by BrummbaerFr** [comment]
Je veux pas de blanc entre les divs principales, que le header soit en haut, que la mainBox prenne toute la page même si elle est vide, et qu'elle continue jusqu'en bas où il y a le footer.
Opération réussie quant au footer, il y a juste la mainBox qui ne prend pas toute la place disponible, donc un autre problème à régler.

**Comment by BrummbaerFr** [comment]
On a ça en gros là

<a href="http://zupimages.net/viewer.php?id=16/09/9maf.png"><img src="http://zupimages.net/up/16/09/9maf.png" alt="" /></a>

Il faudrait que la mainBox prenne tout l'espace vertical jusqu'à toucher le footer
