### ISSUE TITLE
Code Cesar, dysfonctionnement

### ISSUE THREAD

**Issue by BrummbaerFr** [BrummbaerFr/hARDcipher#7]
@snakypex 

Codage de 

> BONJOUR JE M'APPELLE RICHARD ET JE SUIS ISLANDAIS, J'ADORE LES POMMES DE TERRES ÉCOSSAISES

avec une clé de 8, renvoie :

> JWVRWCZ RM U/IXXMTTM ZQKPIZL MB RM ACQA QATIVLIQA4 R/ILWZM TMA XWUUMA LM BMZZMA ÑKWAAIQAMA

Il faudrait supprimer les caractères spéciaux (apostrophes) et aussi casser les accents (voir première lettre du dernier mot chiffré). `to.UpperCase()` ne supprime donc pas les accents.

**Comment by snakypex** [comment]
Je suis regarde ça quand je serais chez moi ;)

**Comment by BrummbaerFr** [comment]
J'ai trouvé une fonction qui supprime les accents sur internet : https://gist.github.com/alisterlf/3490957
Tu peux la bidouiller pour l'intégrer au code
